language: php

git:
  depth: 50

matrix:
  include:
    - php: 5.6
    - php: 7.0
    - php: 7.1
      env: LINT=true
    - php: 7.2
    - php: nightly
      env: NIGHTLY=true
  allow_failures:
    - php: nightly

cache:
  directories:
    - $HOME/.composer/cache/files
    - $HOME/.php-cs-fixer

install:
- phpenv config-rm xdebug.ini || true
- travis_retry composer self-update
- if [[ $NIGHTLY = true ]]; then
    composer remove --dev friendsofphp/php-cs-fixer;
    composer validate;
  fi
- travis_retry composer install --no-interaction
- travis_retry composer dump-autoload --optimize

script:
- if [[ $LINT = true ]]; then
    composer validate;
    composer composer-silent-command-plugin:cs-lint;
  fi
- if [[ $(( $TRAVIS_BUILD_NUMBER % 10 )) = 0 ]]; then
    composer composer-silent-command-plugin:test-all;
  else
    composer composer-silent-command-plugin:test;
  fi

sudo: false

notifications:
  email:
    on_success: change
    on_failure: change
  slack:
    on_success: always
    on_failure: always
    secure: cVXDrEznJRrmsZfc6sQDOVaj52gb4BDWrd13WankpY8AqA1ocHG9NhjbPhNsfCXFgvr7kta2mhFdJXoRILzfeBDotFRXE4zp55fiYleastY6QaP+EhUybZyWxGqBAWb9fPld1f5PwYpVWVcs+BiBb43K8ZZluSzGaiYeT4kKKlsflWQEOvTVErQr65GWGcPt0jE2r7etF1AoJ4QrVc+w1JnyJkvJ7ifi15zyV4XzGSYuP2HtYRs3XvYy6EDgvXh2l24NpyRq4uERlTJpiIyTQ80pXdsq8hXCxNfXDLqQyxXb9DPIMPmkBf/qds+SBTiwL9JMGbOHm5Hpoqotqg43hFNVhMe75bjjhLQ+TRu0JYqWf2I54E71q+7CnyJNcUIg7d/vmX/Ci9atyahoEnyrtXuL+LG//r+94NXqameZ/t2oBoHsDn72CfAMI/ZqxB9Tzk0Kf1wnkzxQwxCGwVzczP3LCpvhcNoM5TX4SbE83JHGo6dDMLOLHiCrrPTvENvvwOXjHGLRGGYNUedebNX840PlHzO4jc/JH4C7YrMlk/RNrejkHVnZiEZNHMpWFnS7u09bTHFwUTFxMnmt0D7TylIQ30Mcc4NWU2aVrjLtkqC0oFWcjDmA1JdyOzj92w8Bsr35an8IQazZfF2GofTsxphAdDfUqWq0dpjwb01VLxU=
